name: Update rusEFI Reference

on:
  workflow_call:

jobs:
  update-git:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git Checkout Submodules
        run: |
          git submodule update --init --depth=1 ext/devops-sandbox-rusefi

      - name: Git Update Submodules
        run: |
          git submodule update --remote

      - name: Commit fresh submodules
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub git update Action"
          OUT=$(git add ext/devops-sandbox-rusefi 2>&1) || echo "commit failed, finding out why"
          if echo "$OUT" | grep 'nothing to commit'; then
            echo "submodule: looks like nothing to commit"
            echo "NOCOMMIT=true" >> $GITHUB_ENV
            exit 0
          elif echo "$OUT" | grep 'changed'; then
            echo "submodule: looks like something has changed"
            exit 0
          else
            echo "submodule: looks like something unexpected"
            exit 1
          fi
          git status

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}

